bucket_85/xorg-driver-input-mouse/specification, bucket_A8/ede/specification, bucket_B6/gts/specification
Marking two ports broken that I have no idea on how to fix:
gts fails to build on fbsd. Log file contains this suspicious line:
`checking whether the c++ linker (/raven/toolchain/bin/ld) supports shared libraries... no`
Debugging the Ravenports toolchain is way above my head unfortunately...
xorg-driver-input-mouse cannot be built on Linux. Here's what goes wrong:
`/raven/toolchain/bin/ld: cannot find -lusbhid`
I did some reading on this one. Looks like libusbhid doesn't exist on Linux systems. I have no idea why Ravenports wants to link the driver against it, though.
----
You've probably overlooked my question regarding reporting of broken ports. Is this kind of "reporting" (adding the BROKEN keyword and issuing a pull request) how you would like things to go? Or would opening an issue …
=> Marking ports as broken

bucket_A0/mpc/patches/patch-configure.ac, bucket_A0/mpc/patches/patch-src_mul.c, bucket_A0/mpc/specification
Create patches from upstream changes that resolve the symbol conflict with mpfr 4.0.0 (#27).
=> Resolve symbol conflict when building mpc against mpfr 4.0.0

bucket_4A/llvm50/specification, bucket_B9/llvm40/specification
It gets overwritten by the standard CMAKE_BUILD_TYPE setting of
"USES=cmake" which is "Release". Changing it's value would have no
effect.
=> Remove -DCMAKE_BUILD_TYPE from CMAKE_ARGS. Use CMAKE_BUILD_TYPE instead.

bucket_5E/doas/descriptions/desc.single, bucket_5E/doas/distinfo, bucket_5E/doas/manifests/plist.single, bucket_5E/doas/specification
Sorry for pull-requesting a port that does not compile yet (at least for me) but I'm having a problem with ravenadm and I don't know if it's something wrong in the specification, a bug in ravenadm or something else.
I written the specification for the doas port (and it seems fine to me) but when I test the package ravenadm stops itself on building aspell-fo (why?) and shows a "banner" at the top with "Graceful shutdown in progress, so no new tasks will be started.". I tried killing ravenadm, rebooting, pressing random keys but nothing seems to unlock the situation.
I think is a problem with the specification because ravenadm builds other ports just fine.
Thanks and apologies again for pr'ing a non-finished port.
=> new port + trouble

bucket_EE/openssh/specification
Disabling ldns indeed fixes OpenSSH on FreeBSD even when linked against LibreSSL.
=> Unbreak OpenSSH

bucket_B4/ravensys-root/files/Makefile, bucket_B4/ravensys-root/manifests/plist.single.freebsd64
Now that kenv.h is available, only libprocstat is missing to successfully build consolekit on fbsd. Is this change ok?
=> Add libprocstat to freebsd64 sysroot

bucket_F9/dmidecode/descriptions/desc.single, bucket_F9/dmidecode/distinfo, bucket_F9/dmidecode/dragonfly/patch-dmidecode.c, bucket_F9/dmidecode/files/dmidecode.in, bucket_F9/dmidecode/freebsd/patch-dmidecode.c, bucket_F9/dmidecode/manifests/plist.single, bucket_F9/dmidecode/specification
Please have a look at this port and try it out on dfly - I just copied the patch from dports but don't have any Dragonfly machine at hand. I left out the Makefile patch from the FPC since the port builds without it and to me it seemed only relevant to make dmidecode build with FreeBSD's clang.
BTW: The FreeBSD port has another file, dmidecode.in. How should periodic scripts be treated? Do we want those? If yes: Can they just be copied over or is this a bit much to take in addition to patches?
If we don't want that additional file and the port works on dfly, it can be committed. (Unless you want me to remove the "DOC" files installed by default or something like that.)
=> Add dmidecode

bucket_DC/siren/descriptions/desc.single, bucket_DC/siren/distinfo, bucket_DC/siren/manifests/plist.single, bucket_DC/siren/patches/patch-compat_tree.h, bucket_DC/siren/specification
Text-based audio player.
TODO:
* port opusfile and add opus support.
* add options for output backend (not necessary, it's better to use cross-platform sndio, libav and/or portaudio).
* improve description? (I don't like the one taken from FreeBSD)
=> add siren port

bucket_B4/maim/descriptions/desc.single, bucket_B4/maim/distinfo, bucket_B4/maim/manifests/plist.single, bucket_B4/maim/specification, bucket_CB/slop/descriptions/desc.single, bucket_CB/slop/distinfo, bucket_CB/slop/manifests/plist.single, bucket_CB/slop/specification
I was going to actually port scrot and its dependency giblib, but I changed my mind and thanks to description I know scrot is abandonware and maim is a better option, so here I port maim screenshooter and its dependency slop. 
Tested at DragonFlyBSD :)
=> add slop and maim ports

bucket_39/opus-tools/descriptions/desc.single, bucket_39/opus-tools/distinfo, bucket_39/opus-tools/manifests/plist.single, bucket_39/opus-tools/specification, bucket_D8/libopusenc/descriptions/desc.primary, bucket_D8/libopusenc/distinfo, bucket_D8/libopusenc/manifests/plist.primary, bucket_D8/libopusenc/specification
Opus-tools provides command-line utilities to encode, inspect, and decode .opus files.
libopusenc is opus-tools's new dependency.
Don't hurry to merge, opus-tools is multi licensed and stores both BSD and GPL in one file and that causes error at test, adding GPLv2:stock didn't help :/
Tested at DragonFlyBSD
=> add libopusenc and opus-tools ports

bucket_27/wtf/specification, bucket_57/aspell-ro/specification
The only port left is a52dec, but unfortunately it's impossible to do that for it, it's files directory at sourceforge is empty.
=> wtf and aspell-ro: use SF shortcut in SITES

bucket_F0/mesa/dragonfly/patch-src_mesa_drivers_dri_i965_brw__bufmgr.c
* It is broken with current DragonFly 5.4 and 5.5 kernels
* This patch is a revert of Mesa's a363bb2cd0e2a141f2c60be005009703bffcbe4e
"i965: Allocate VMA in userspace for full-PPGTT systems."
=> graphics/mesa-dri: Disable soft-spinning of all buffers

bucket_1C/fdm/specification
https://github.com/nicm/fdm/pull/49
https://github.com/nicm/fdm/commit/f90a5b0cc8d881ddb886c74c5bff510a56f2ba74
=> fdm: VAR_OPSYS[dragonfly] is no longer needed

bucket_30/warsow/distinfo, bucket_30/warsow/manifests/plist.single, bucket_30/warsow/specification
First, openal is only a build dependency, in my fork I removed dlopen()'ing system-wide libraries. Second, it plays sound via snd_qf anyway (via sdl).
=> warsow: remove snd_openal module

bucket_30/warsow/distinfo, bucket_30/warsow/manifests/plist.single, bucket_30/warsow/specification
So, here are some improvements:
* removed useless steamlib module;
* all compiler warnings coming from Clang with -Wall -Werror are silenced;
* synced with warsow_2.1 branch from upstream (it contains bugfixes since release);
* few bugfixes from me, I mostly fixed conditions which always evaluate to true;
* install target is now in CMakeLists.txt;
* added -fpic flag to build at FreeBSD.
=> Improve warsow port.

bucket_30/warsow/distinfo, bucket_30/warsow/specification
I didn't think I'd fix this game one more time, but at least now FPS limiter works properly at OpenBSD, the whole problem was OpenBSD is not tickless, OpenBSD allows to sleep for 10 milliseconds and more. All I did was just [removing code](https://github.com/OrangeGrayCyan/warsow/commit/58d690e920359857f984ad1112712c0d6a7b7d8a), now this game will never sleep and that's ok.
=> Warsow: Fix FPS limiter by removing sleeps.

bucket_51/cyrus-sasl/specification
- fetching failed / timed out
```shell
--------------------------------------------------------------------------------
--  Phase: fetch
--------------------------------------------------------------------------------
===>  Fetching for cyrus-sasl-standard
=> cyrus-sasl-2.1.27.tar.gz doesn't seem to exist in /distfiles.
=> Attempting to fetch http://cyrusimap.org/releases/cyrus-sasl-2.1.27.tar.gz
http://cyrusimap.org/releases/cyrus-sasl-2.1.27.tar.gz: Not Found
=> Attempting to fetch ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.27.tar.gz
ftp://ftp.cyrusimap.org/cyrus-sasl/cyrus-sasl-2.1.27.tar.gz: Operation timed out
=> Attempting to fetch https://github.com/cyrusimap/cyrus-sasl/releases/download/cyrus-sasl-2.1.27/cyrus-sasl-2.1.27.tar.gz
cyrus-sasl-2.1.27.tar.gz …
```
=> cyrus-sasl: add alternative download location ( via github )

bucket_D1/pcre/specification
As per issue #230, pcre no longer maintains their FTP mirror for downloading package. To maintain pcre and not pcre2, must pull packages from their source forge site.
Fetch logs from `/var/ravenports/primary/logs/logs/pcre___standard.log` on NetBSD
```
--------------------------------------------------------------------------------
--  Phase: fetch
--------------------------------------------------------------------------------
===>  Fetching for pcre-standard
=> pcre-8.45.tar.bz2 doesn't seem to exist in /distfiles.
=> Attempting to fetch https://sourceforge.net/projects/pcre/files/pcre/8.45/pcre-8.45.tar.bz2
pcre-8.45.tar.bz2                                     1541 kB  304 kBps    05s
```
=> pcre: update download site

bucket_D1/pcre/specification
Left off a back slash on the end, otherwise ravenadm fails to fetch
=> pcre: format properly for fetch phase

bucket_80/comtrya/specification, bucket_80/comtrya/specification.template
We added it back when @kraileth brought it to my attention that it was left out when the project was split into workspaces.
https://github.com/comtrya/comtrya/commit/0984be459011f09fd052959d251ba3b974a02ef3
=> add license field back to comtrya

bucket_7F/libmicrohttpd/specification
Removed not needed dependency (libgcrypt)
Disabled build of tools.
Force enabled HTTPS to avoid accidental disable
=> libmicrohttpd: fix specification

bucket_F0/mesa/manifests/plist.primary, bucket_F0/mesa/specification
Fixes: https://github.com/Ravenports/ravensource/issues/331
Prior to this commit, glxinfo would report:
~ % glxinfo
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig
unless mesa-libs from DPorts (DragonFly ports) were found on the system (pkg ins mesa-libs); chromium from DPorts for example depend on this lib.
ktracing "glxinfo" revealed that it is trying to load libGLX_mesa.so. But the latter is only build if libglvnd is found at build time, so this commit just adds libglvnd as a build-time dependency.
GLVND is the vendor neutral interface for GL.
With this commit in place, "glxinfo" properly works.
=> mesa - fix GLX (fixes #331)
